### ISSUE TITLE
[BUG] something not working in SWEET term resolution

### ISSUE THREAD

**Issue by graybeal** [ESIPFed/sweet#191]
## Description

Trying to access SWEET terms isn't working, at least for the first ontology.

http://sweetontology.net/stateSystem/Artificial, for example, gives the result below
<img width="1411" alt="Screen Shot 2020-04-30 at 1 45 04 PM" src="https://user-images.githubusercontent.com/1266896/80757894-bfe9b900-8ae9-11ea-81bd-a03faaa950f7.png">

**Comment by lewismc** [comment]
I can't reproduce this.

**Comment by carueda** [comment]
Just did some inspection:

```
$ docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                      NAMES
942770f1d977        mmisw/orr:3.9.3          "catalina.sh run"        3 weeks ago         Up 3 weeks          0.0.0.0:9090->8080/tcp     orr
7dfdbdd1d6ce        franzinc/agraph:v6.1.1   "/bin/sh -c '/app/ag…"   7 weeks ago         Up 7 weeks          0.0.0.0:10035->10035/tcp   agraph
3a26e98b3e3c        mongo:3.4.2              "docker-entrypoint.s…"   7 weeks ago         Up 7 weeks          0.0.0.0:27017->27017/tcp   mongo
```

```
$ctop
```
> ![image](https://user-images.githubusercontent.com/556505/80759553-56b77500-8aec-11ea-986f-36d74b7e7358.png)

```
$ docker logs -f agraph
...
[2020-04-30T15:45:45.284 p40 E spawn] Process 'mmiorr instance' raised: 
   writing buffer for #<excl.osi::pipe-writing-simple-stream  
  for output fd 14 @ #x100050f72e2> resulted in error (code 32): Broken pipe.
```
That's the last piece of output at this point .. Not sure whether it's related and what it means.

Let's try restarting the agraph container:

```
[cor-admin1@ip-172-31-12-159]$ cd COR
[cor-admin1@ip-172-31-12-159 COR]$ source setenv.sh
[cor-admin1@ip-172-31-12-159 COR]$ docker-compose restart agraph
```

Yes, that seems to have "fixed" the issue.

![image](https://user-images.githubusercontent.com/556505/80760308-8915a200-8aed-11ea-8cd9-7ad23e96de92.png)

("Fixed" at least for this case.  A more proper fix, mentioned already a few times on various occasions involves a combination of upgrading AGraph and perhaps tuning up some settings, like timeouts, some of them on the ORR backend itself..)

(btw, this issue was not SWEET-specific, but on the COR isntance in general.)

**Comment by lewismc** [comment]
<img width="1680" alt="Screen Shot 2020-04-30 at 2 21 28 PM" src="https://user-images.githubusercontent.com/1165719/80760556-ef022980-8aed-11ea-9650-403b5be4928a.png">
