### ISSUE TITLE
'opm' namespace prefix no longer exists within reprSciProvenance.owl

### ISSUE THREAD

**Issue by lewismc** [ESIPFed/sweet#26]
The following code is present within **reprSciProvenance.owl**,
```
...
  <!ENTITY pmljbase "http://inference-web.org/2.0/pml-justification.owl#">
  <!ENTITY pmlj "http://inference-web.org/2.0/pml-justification.owl#">
  <!ENTITY pmlpbase "http://inference-web.org/2.0/pml-provenance.owl#">
  <!ENTITY opm "http://openprovenance.org/ontology/opm.owl#">
...
```
You can see that http://openprovenance.org/ontology/opm.owl no longer exists, we should address this.

**Comment by lewismc** [comment]
The new file is located at 

http://openprovenance.org/model/opmo-20101012.owl

it is referenced at http://openprovenance.org/model/opmo#ref-opm-v1.1

**Comment by rduerr** [comment]
This is why each and every term in an ontology needs a permanent and unique URL - forget all this namespace nonsense!!!!  Just use YAMZ to give each term both an ARK (maintained by multiple organizations internationally for the long-term) and a human readable definition.

Terms need the equivalent of an ORCID or DOI for the same reason that people and articles do.  

Ruth

**Comment by graybeal** [comment]
I'm afraid I don't agree with that analysis, Ruth. (Might be a discussion for the semantic committee I suppose.)

Terms already have the equivalent of an ORCID or DOI. The principle of the semantic web is that the URIs provided by the ontology ARE the equivalent of ORCIDs or DOIs: they are meant to be permanent, and they are meant to be unique. It is not required that they be resolvable for them to be used as identifiers. But it is required that they have identifiers defined by RDF, OWL, or similar, and many of the features of those specifications and their tools (e.g., namespaces) directly support the easy creation, understanding, and management of that type of identifier.

To take this case, the existence of a namespace is not why the ontology 'broke'—a namespace is simply a shorthand way to refer to the full unique identifier. And the original full unique identifer remains a valid identifier, the problem is just that the owner/maintainer of the ontology broke the ability to access the file or resoolve the URI(s). On the other hand, it has always been the case with this technology that the file may or may not be located at the path of its term URIs, and that the URIs do not have to be resolvable. In fact, if the ontology term names haven't been changed, everything should still work fine in SWEET as long as the address of the ontology is changed—in and of itself, that doesn't change the namespace of the ontology and its terms.  (And if the term names have been changed, the provider is clearly defining a new ontology, in my humble opinion.)

There are several other "best practices" that were broken by the ontology owners/maintainers.

First, if an ontology's URIs move from one namespace to another, that raises a significant doubt about whether it is in principle the same ontology. I would suggest that any such move should prompt a review by all the users of that ontology, since likely the owning organization and perhaps philosophy has changed.

Second, if the maintainers of an ontology move the ontology, and don't keep the old ontology serviced or at least auto-forwarded to the new ontology, that is telling me something about their commitment to maintain a permanently available resource. This was the reason for creating a repository, like COR or BIoPortal, in the first place -- the repository is meant to carry the long-term commitment, so the author doesn't have to.

Third, the original URIs are still valid, even if the ontology which declared them is no longer available. That doesn't help with parsing, but ARKs, DOIs, etc. won't help with parsing either.

Fourth, the existence of an ARK, or DOI, does not carry any more weight to the actual maintenance of the actual artifact than the existence of a semantic URI. If the original creator violates best maintenance practices like changing the ontology's name space or moving the file without maintaining a forward reference, there is nothing that keeps them from doing exactly the same thing with an ontology that has a bunch of ARK or DOI identifiers. They might even generate all new identifiers to reflect the new namespace, or fail to update the references in the ARK or DOI catalogs.

Not to mention that the Name Mapping Authority part of the ARK names can actually change the same way URI paths changed in this case ("without affecting the object's identify", per https://confluence.ucop.edu/display/Curation/ARK). So it seems to me that would break the ontology in exactly the same way. (DOIs, not being inherently resolvable in the first place, don't suffer from that problem; I'm not sure what happens if the DOI service you registered your metadata with goes belly up.)

I apologize in advance if there is anything seriously wrong in my understanding of these technologies. I've been trying to fully appreciate their advantages and disadvantages for 15 years now, and I'm open to hearing that my understanding of the way they work is wrong.


On Jul 27, 2017, at 1:05 PM, rduerr <notifications@github.com<mailto:notifications@github.com>> wrote:

This is why each and every term in an ontology needs a permanent and unique URL - forget all this namespace nonsense!!!! Just use YAMZ to give each term both an ARK (maintained by multiple organizations internationally for the long-term) and a human readable definition.

Terms need the equivalent of an ORCID or DOI for the same reason that people and articles do.

Ruth

Sent from my iPad

> On Jul 27, 2017, at 4:00 PM, Lewis John McGibbney <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> The new file is located at
>
> http://openprovenance.org/model/opmo-20101012.owl
>
> it is referenced at http://openprovenance.org/model/opmo#ref-opm-v1.1
>

========================
John Graybeal
Technical Program Manager
Center for Expanded Data Annotation and Retrieval /+/ NCBO BioPortal
Stanford Center for Biomedical Informatics Research
650-736-1632
skype: graybealski
