### ISSUE TITLE
Updating GCMD Science Keywords in the COR

### ISSUE THREAD

**Issue by tbs1979** [ESIPFed/sweet#80]
I am trying to update the GCMD Science Keyword Version in the http://cor.esipfed.org and when I try to save the file, I get the following error '"<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>502 Proxy Error</title>\n</head><body>\n<h1>Proxy Error</h1>\n<p>The proxy server received an invalid\r\nresponse from an upstream server.<br />\r\nThe proxy server could not handle the request <em><a href=\"/ont/api/v0/ont\">PUT&nbsp;/ont/api/v0/ont</a></em>.<p>\nReason: <strong>Error reading from remote server</strong></p></p>\n</body></html>\n"'. I am also trying the update the URL to https://gcmdservices.gsfc.nasa.gov/kms/concepts/concept_scheme/sciencekeywords/

![image](https://user-images.githubusercontent.com/25930554/35517621-0086856e-04dd-11e8-9853-285ae65ccbe7.png)

**Comment by carueda** [comment]
@tbs1979 Hi Tyler.

I'm not seeing any errors in the logs.  Could you provide a bit of more detail about the sequence that ended up at this error message?  Being able to reproduce this would be key to address the issue.

**Comment by tbs1979** [comment]
I go to http://cor.esipfed.org/ont?iri=http://gcmdservices.gsfc.nasa.gov/kms/concepts/concept_scheme/sciencekeywords > Edit New Version > Edit Metadata > Original Source tab > Edit Version '8.6' > Register > Proceed with registration

**Comment by tbs1979** [comment]
Is there a different way to update the version of the keywords in the registration?

**Comment by carueda** [comment]
@tbs1979  Thanks Tyler.   I was just able to reproduce the problem so I can go ahead with closer investigation. I'll let you know once I have news.

----
**Meta-comment**

(@tbs1979 Tyler, sorry for the little "noise" here, I'll remove this part once we, the COR team, can address this management aspect.)

@graybeal, @lewismc  Hi Lewis, John:

I think we should discuss about defining a primary repo for issues regarding COR (I thought that could have been https://github.com/ESIPFed/cor but it seems it is not(?)).  Anyway, the rough core idea is:
- COR users will (in principle, at least) use that specific repo as the first place to report errors
- COR maintainers will determine whether the issue is about the COR itself (eg, configuration), or whether it actually involves a bug in the ORR software. If the latter, then submission of the issue to the relevant ORR issue tracker should be entered

**Comment by lewismc** [comment]
@carueda looks like this was dropped. Where can this be logged to get it out of SWEET?

**Comment by carueda** [comment]
@lewismc Thanks for the reminder Lewis.  I just "moved" this issue to https://github.com/ESIPFed/cor/issues/56
